# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Midtown Counselling
email: info@midtowncounselling.ca
description: >- # this means to ignore newlines until "baseurl:"
  Living with a dark, stormy cloud over your head is NO way to live. If your cloud is taking
  away from your personal life or career, you may feel burdened, alone or misunderstood.
  It doesn’t have to be that way. Psychotherapy techniques like Cognitive Behavioural
  Therapy (CBT) and Mindfulness Therapy relieve anxiety, depression and stress, restore
  confidence, foster effective relationships, and unlock personal potential.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://midtowncounselling.ca" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: shellypavlic
facebook_username: midtowncounselling.ca

show_excerpts: true

# Build settings
theme: minima
plugins:
  - jekyll-feed

minima:
  date_format: "%B %-d, %Y"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#

sass:
  style: compressed

exclude:
  - Makefile
  - README.md
  - run.bat
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
